# Generated by Django 3.2.8 on 2024-06-06 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20240606_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='delete_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
